/**
 * Centralized error codes for consistent API responses.
 * Use these constants when throwing AppError to ensure consistent client handling.
 */
export const ErrorCodes = {
  // 4xx — Client errors
  INVALID_INPUT: "INVALID_INPUT",
  NOT_FOUND: "NOT_FOUND",
  NOT_DIRECTORY: "NOT_DIRECTORY",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  INVALID_KEY: "INVALID_KEY",
  INVALID_AGENT_CONFIG: "INVALID_AGENT_CONFIG",
  ALREADY_OPENSPRINT_PROJECT: "ALREADY_OPENSPRINT_PROJECT",
  NO_GATE_TASK: "NO_GATE_TASK",
  TASKS_IN_PROGRESS: "TASKS_IN_PROGRESS",
  TASKS_NOT_COMPLETE: "TASKS_NOT_COMPLETE",
  NO_EPIC: "NO_EPIC",
  DECOMPOSE_PARSE_FAILED: "DECOMPOSE_PARSE_FAILED",
  DECOMPOSE_JSON_INVALID: "DECOMPOSE_JSON_INVALID",
  DECOMPOSE_EMPTY: "DECOMPOSE_EMPTY",

  // 404 — Not found
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PRD_NOT_FOUND: "PRD_NOT_FOUND",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  SECTION_NOT_FOUND: "SECTION_NOT_FOUND",
  SETTINGS_NOT_FOUND: "SETTINGS_NOT_FOUND",
  FEEDBACK_NOT_FOUND: "FEEDBACK_NOT_FOUND",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  ISSUE_NOT_FOUND: "ISSUE_NOT_FOUND",
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",

  // 5xx — Server / external service errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  TASK_STORE_INIT_FAILED: "TASK_STORE_INIT_FAILED",
  TASK_STORE_WRITE_FAILED: "TASK_STORE_WRITE_FAILED",
  TASK_STORE_TIMEOUT: "TASK_STORE_TIMEOUT",
  TASK_STORE_PARSE_FAILED: "TASK_STORE_PARSE_FAILED",
  TASK_STORE_CLOSE_FAILED: "TASK_STORE_CLOSE_FAILED",
  TASK_STORE_CREATE_FAILED: "TASK_STORE_CREATE_FAILED",
  ENV_WRITE_FAILED: "ENV_WRITE_FAILED",

  // Scaffold errors
  SCAFFOLD_INIT_FAILED: "SCAFFOLD_INIT_FAILED",

  // Agent errors
  AGENT_UNSUPPORTED_TYPE: "AGENT_UNSUPPORTED_TYPE",
  AGENT_TASK_FILE_READ_FAILED: "AGENT_TASK_FILE_READ_FAILED",
  AGENT_CLI_REQUIRED: "AGENT_CLI_REQUIRED",
  AGENT_INVOKE_FAILED: "AGENT_INVOKE_FAILED",
  ANTHROPIC_API_KEY_MISSING: "ANTHROPIC_API_KEY_MISSING",
  CURSOR_API_ERROR: "CURSOR_API_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
