/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["selector", 'html[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        /* Theme-aware tokens (map to CSS variables in index.css) */
        theme: {
          bg: "var(--color-bg)",
          "bg-elevated": "var(--color-bg-elevated)",
          text: "var(--color-text)",
          muted: "var(--color-text-muted)",
          surface: "var(--color-surface)",
          border: "var(--color-border)",
          "border-subtle": "var(--color-border-subtle)",
          ring: "var(--color-ring)",
          "input-bg": "var(--color-input-bg)",
          "input-text": "var(--color-input-text)",
          "input-placeholder": "var(--color-input-placeholder)",
          "code-bg": "var(--color-code-bg)",
          "code-text": "var(--color-code-text)",
          overlay: "var(--color-overlay)",
          "surface-muted": "var(--color-surface-muted)",
          "graph-edge": "var(--color-graph-edge)",
          "graph-edge-critical": "var(--color-graph-edge-critical)",
          /* Semantic tokens */
          "error-bg": "var(--color-error-bg)",
          "error-text": "var(--color-error-text)",
          "error-border": "var(--color-error-border)",
          "error-solid": "var(--color-error-solid)",
          "error-solid-hover": "var(--color-error-solid-hover)",
          "success-bg": "var(--color-success-bg)",
          "success-text": "var(--color-success-text)",
          "success-border": "var(--color-success-border)",
          "success-solid": "var(--color-success-solid)",
          "success-muted": "var(--color-success-muted)",
          "warning-bg": "var(--color-warning-bg)",
          "warning-text": "var(--color-warning-text)",
          "warning-border": "var(--color-warning-border)",
          "warning-solid": "var(--color-warning-solid)",
          "info-bg": "var(--color-info-bg)",
          "info-text": "var(--color-info-text)",
          "info-border": "var(--color-info-border)",
          "info-solid": "var(--color-info-solid)",
          "notification-error": "var(--color-notification-error)",
          "notification-warning": "var(--color-notification-warning)",
          "notification-info": "var(--color-notification-info)",
          "notification-success": "var(--color-notification-success)",
          "feedback-bug-bg": "var(--color-feedback-bug-bg)",
          "feedback-bug-text": "var(--color-feedback-bug-text)",
          "feedback-feature-bg": "var(--color-feedback-feature-bg)",
          "feedback-feature-text": "var(--color-feedback-feature-text)",
          "feedback-ux-bg": "var(--color-feedback-ux-bg)",
          "feedback-ux-text": "var(--color-feedback-ux-text)",
          "feedback-scope-bg": "var(--color-feedback-scope-bg)",
          "feedback-scope-text": "var(--color-feedback-scope-text)",
          "status-backlog": "var(--color-status-backlog)",
          "status-ready": "var(--color-status-ready)",
          "status-in-progress": "var(--color-status-in-progress)",
          "status-in-review": "var(--color-status-in-review)",
          "status-done": "var(--color-status-done)",
          "status-blocked": "var(--color-status-blocked)",
        },
        brand: {
          50: "#f0f7ff",
          100: "#e0effe",
          200: "#b9dffd",
          300: "#7cc5fc",
          400: "#36a8f8",
          500: "#0c8de9",
          600: "#006fc7",
          700: "#0059a2",
          800: "#054b85",
          900: "#0a3f6e",
          950: "#072849",
        },
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Menlo", "monospace"],
      },
      keyframes: {
        "slide-up-fade": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-out-fade": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(-8px)" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "slide-in-left": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "logo-pulse": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "slide-up-fade": "slide-up-fade 0.2s ease-out",
        "slide-out-fade": "slide-out-fade 0.2s ease-out forwards",
        "slide-in-right": "slide-in-right 0.2s ease-out",
        "slide-in-left": "slide-in-left 0.2s ease-out",
        "fade-in": "fade-in 0.15s ease-out",
        "logo-pulse": "logo-pulse 1.2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
